services:
  mongodb:
    image: mongo:8.0
    container_name: blog-mongodb
    command:
     - mongod
     - --replSet
     - rs0
     - --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - blog-mongo-data:/data/db
volumes:
  blog-mongo-data: